SSAFY/03_django/CRUD_TEMP/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # NEW(GET) + CREATE(POST)
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'), # EDIT(GET) + UPDATE(POST)
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'), # DETAIL(GET) + CREATE(POST)
    path('<int:article_pk>/<int:comment_pk>/comments_delete/', views.comments_delete, name='comments_delete'), # DETAIL(GET) + DELETE(POST)
]

SSAFY/03_django/CRUD_TEMP/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jobs/', include('jobs.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

SSAFY/03_django/CRUD_TEMP/jobs/urls.py
from django.urls import path
from . import views


app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

SSAFY/03_django/CRUD_TEMP/articles/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        # return f'/articles/{self.pk}/'
        return reverse('articles:detail', kwargs={'article_pk': self.pk}) # /articles/10/
        '''
        딕셔너리로 작성할 때
        return reverse('articles:detail', kwargs={'pk':self.pk}) # /articles/10/
        '''
        # 주의사항
        # reverse 함수에 args랑 kwargs를 동시에 인자로 보낼 수 없다.


class Comment(models.Model):
    # comment_set 붙이는 것을 comments로 바꾸려면 --> , related_name='comments' 추가
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # 가장 최신 댓글이 가장 위에 올라오도록
        ordering = ['-pk']

    def __str__(self):
        # return self.content
        return f'<Article({self.article_id}): Comment({self.pk})-{self.content}'


class Question(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Choice(models.Model):
    content = models.CharField(max_length=15)
    votes = models.IntegerField()

    def __str__(self):
        return self.content

SSAFY/03_django/CRUD_TEMP/jobs/models.py
from django.db import models

# Create your models here.

class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    def __str__(self):
        return self.name

SSAFY/03_django/CRUD_TEMP/articles/views.py
from IPython import embed
# embed : 서버 잠깐 멈추게하는 것
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from .models import Article, Comment

# Create your views here.
# READ 해오기 위한 작업
def index(request):
    # 역순으로 받으려면 .order_by('-')
    articles = Article.objects.all().order_by('-pk') # DB가 변경
    # articles = Article.objects.all()[::-1] # python이 변경
    context = {'articles': articles,}
    return render(request, 'articles/index.html', context)


# 직접적으로 모델에 저장하는 역할
def create(request):
    # CREATE
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content') 
        article = Article(title=title, content=content)
        article.save()
        return redirect(article)
    # NEW
    else:
        return render(request, 'articles/create.html')


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comment_set.all()
    # article.get_absolute_url()
    context = {'article': article, 'comments': comments,}
    return render(request, 'articles/detail.html', context)


def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)


def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        context = {'article': article,}
        return render(request, 'articles/update.html', context)


def comments_create(request, article_pk):
    # 댓글을 달 게시글이 필요
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        # form에서 넘어온 댓글 정보 받아오기
        content = request.POST.get('content')
        # 댓글 생성 및 저장
        comment = Comment(article=article, content=content)
        comment.save()
        return redirect(article)
        # 다른 방식 (get_absolute_url을 구현하지 못했을 경우)
        # return redirect('articles:detail' article.pk)
        # return redirect('articles:detail' article_pk)
    else:
        return redirect(article)


def comments_delete(request, comment_pk, article_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
    return redirect('articles:detail', article_pk)

'''
def comments_delete(request, comment_pk, article_pk):
    article = Article.objects.get(pk=article_pk)
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
    return redirect(article)
'''

SSAFY/03_django/CRUD_TEMP/jobs/views.py
from django.shortcuts import render
from faker import Faker
import requests
from .models import Job
from pprint import pprint
from decouple import config

# Create your views here.

def index(request):
    return render(request, 'jobs/index.html')


def past_life(request):
    # 사용자로부터 이름 데이터를 받음.
    name = request.POST.get('name')

    # DB에 매칭되는 name 가져오기
    '''
    get이 간단하지만 이름이 없을 경우 에러를 발생하기 때문에 사용하지 않음.
    Job.objects.get(name=name)
    '''
    # filter 함수 사용
    # 한개던 0개던 상관없이 무조건 쿼리셋으로 가져옴.(리스트 형식)
    person = Job.objects.filter(name=name).first()

    # DB에 person이 있는지 없는지 판단
    if person:
        past_job = person.past_job
    else: # DB에 기존 이름이 없다면(person이 빈 쿼리셋(==False))
        faker = Faker()
        past_job = faker.job()
        person = Job(name=name, past_job=past_job)
        person.save()

    # GIPHY (past_job을 API에 요청을 보내서 응답을 받음)
    GIPHY_API_KEY = config('GIPHY_API_KEY')
    # 키값 .env로 숨겨서 가져오기
    url = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API_KEY}&q={past_job}&limit=1'
    data = requests.get(url).json()
    # pprint(data)
    # 이미지 없을 때 처리
    try:
        image = data.get('data')[0].get('images').get('original').get('url')
    except IndexError:
        image = None
    context = {'person': person, 'image': image,}
    return render(request, 'jobs/past_life.html', context)

SSAFY/03_django/CRUD_TEMP/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="" method="POST">
  <!-- 인증된 값이라는 것을 알려주기 위해 token 값을 함께 보내야 함 -->
  {% csrf_token %}
  <!-- views.create 에서도 get 받는 방식 변경 -->
  <div class="container p-0">
    <label for="title">TITLE</label>
    </div>
    <input type="text" name="title" id="title"><br>
    <div class="container p-0">
    <label for="content">CONTENT</label>
    </div>
    <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
    <input type="submit" value="submit">
  </form>
{% endblock  %}

SSAFY/03_django/CRUD_TEMP/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">DETAIL</h1>
<h2>{{ article.pk }} 번째 글</h2>
<hr>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>작성 시간 : {{ article.created_at }}</p>
<p>수정 시간 : {{ article.updated_at }}</p>
<hr>
<!-- 댓글 출력 -->
<p><b>{{ comments|length }}개의 댓글</b></p>
<!-- count 메서드가 호출되면서 comment 모델 쿼리를 한번 더 db에 보내기 때문에 속도가 더 느리다. -->
<p><b>{{ comments.count }}개의 댓글</b></p>
<!-- comments가 안넘어올 때 사용 가능 -->
<p><b>{{ article.comment_set.all|length }}개의 댓글</b></p>
<p> 댓글 목록
  {% for cmm in comments %}
  <li>{{ cmm.content }}
    <form action="{% url 'articles:comments_delete' article.pk cmm.pk %}" method="POST" style="display: inline;">
      {% csrf_token %}
      <input type="submit" value="del">
    </form>
  </li>
  {% empty %}
  <p><b>댓글이 없습니다.</b></p>
  {% endfor %}
</p>
<hr>
<!--
{% for choice in choices %}
  <h3>{{ choice.content }}</h3>
  <h3>{{ choice.votes }}</h3>
{% endfor %}
-->
<!-- 댓글 작성 form -->
<form action="{% url 'articles:comments_create' article.pk %}" method="POST">
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울거야?')">
    {% csrf_token %}
    <label for="content">COMMENT</label>
    <input type="text" name="content" id="content">
    <input type="submit" value="submit">
  </form>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
  <input type="submit" value="DELETE">
</form>

<a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock  %}

SSAFY/03_django/CRUD_TEMP/articles/templates/articles/index.html
{% extends 'base.html' %} 

{% block content %}
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'articles:create' %}">[NEW]</a>
  <hr>
  {% comment %} for문 돌려서 해당하는 값들을 차례로 출력 {% endcomment %}
  {% for article in articles %}
    <p>글 번호 : {{ article.pk }}</p>
    <p>글 제목 : {{ article.title }}</p>
    <p>글 내용 : {{ article.content }}</p>
    <a href="{{ article.get_absolute_url }}">[DETAIL]</a>
    {% comment %} 똑같이 동작
    <a href="/articles/{{ article.pk }}">[DETAIL]</a>
    번호에 해당하는 글에 들어가는 버튼 작성 {% endcomment %}
    <a href="{% url 'articles:detail' article.pk%}">[DETAIL]</a>
    <hr>
  {% endfor %}
{% endblock  %}

SSAFY/03_django/CRUD_TEMP/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">UPDATE</h1>
  <form action="" method="POST">
  {% comment %} 인증된 값이라는 것을 알려주기 위해 token 값을 함께 보내야 함 {% endcomment %}
  {% csrf_token %}
  {% comment %} views.create 에서도 get 받는 방식 변경 {% endcomment %}
  <div class="container p-0">
    <label for="title">TITLE</label>
    </div>
    <input type="text" name="title" id="title" value="{{ article.title }}"><br>
    <div class="container p-0">
    <label for="content">CONTENT</label>
    </div>
    <textarea name="content" id="content" cols="30" rows="5">{{ article.content }}</textarea><br>
    <input type="submit" value="submit">
  </form>
  <a href="{{ article.get_absolute_url }}">[back]</a>
{% endblock  %}

SSAFY/03_django/CRUD_TEMP/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    {% block content %}
    {% endblock  %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

SSAFY/03_django/CRUD_TEMP/jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block content %}
<h1>전생의 직업</h1>
<p>당신의 전생의 직업을 알려드립니다.</p>

<form action="{% url 'jobs:past_life' %}" method="POST">
  {% csrf_token %}
  <label for="">NAME</label>
  <input type="text" name="name" id="name">
  <input type="submit" value="submit">
</form>

{% endblock %}

SSAFY/03_django/CRUD_TEMP/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ person.name }}님의 전생은 {{ person.past_job }}입니다.</h1>
<img src="{{ image }}" alt="gif_img">
<a href="{% url 'jobs:index' %}">뒤로가기</a>

{% endblock  %}