SSAFY/03_django/03_django_form/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 문자열만 있는 주소를 입력할 때는 최하단에 입력해야한다. (위에 있으면 아래에 있는 주소를 읽지 못함.)
    path('<str:username>', views.profile, name='profile'),
]

SSAFY/03_django/03_django_form/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
]

SSAFY/03_django/03_django_form/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # accounts가 겹치면 우리가 구현한 accounts를 위에 위치하도록
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

SSAFY/03_django/03_django_form/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
# Article 보다 먼저 정의해줘야 아래에서 참조할 수 있다(위쪽에 작성)
class Hashtag(models.Model):
    # 같은 해시태그가 작성되면 안됨.(unique)
    # unique=True인 경우 이 필드는 테이블 전체에서 고유한 값이어야 한다.
    # 유효성 검사 단계에서 실행되며 중복값이 있는 모델을 저장하려고 하면 .save() 메서드로 인해
    # 'IntegrityError'가 발생한다.
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content
    

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    # 해시태그 불러오기 전에 위에서 먼저 저의
    hashtags = models.ManyToManyField(Hashtag, blank=True, )


    class Meta:
        ordering = ('-pk',)
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"article_pk": self.pk})


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.content

SSAFY/03_django/03_django_form/articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10, 
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'my-title',
#                 'placeholder': 'Enter the title',
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': 'Enter the content',
#                 'rows': 5,
#                 'cols': 50,
#             }
#         )
#     )

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        max_length=10,
        widget=forms.TextInput(
            attrs={
                'class': 'my-title', 
                'placeholder': 'Enter the title',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-content',
                'placeholder': 'Enter the content',
                'rows': 5,
                'cols': 50,
            }
        )
    )
    
    class Meta:
        model = Article
        fields = ('title', 'content',)
        # fields = '__all__'
        # exclude = ('user_id',)
        # widgets = {
        #     'title': forms.TextInput(attrs={
        #         'class': 'my-title'
        #     })
        # }


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('content',)

SSAFY/03_django/03_django_form/articles/views.py
import hashlib
from IPython import embed
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse
from django.views.decorators.http import require_POST
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    visits_num = request.session.get('visits_num', 0)
    request.session['visits_num'] = visits_num + 1
    request.session.modified = True
    articles = Article.objects.all()
    context = {'articles': articles, 'visits_num': visits_num,}
    return render(request, 'articles/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            # 해시태그는 글이 저장된 이후에 작성해야된다. (써진 글을 보고 판단해야되기 때문)
            for word in article.content.split(): # content를 공백 기준으로 list로 변경
                if word.startswith('#'): # '#' 으로 시작하는 요소만 선택
                    hashtag, created = Hashtag.objects.get_or_create(content=word) # word와 같은 hashtag를 찾는데, 있으면 기존 객체를 get, 없으면 새로운 객체를 create
                    article.hashtags.add(hashtag) # created를 사용하지 않았다면, hashtag[0]으로 사용 (tuple이기 때문))
            return redirect(article)
    else:
        form = ArticleForm()
    context = {'form': form,}
    return render(request, 'articles/form.html', context)


def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all() # article 의 모든 댓글
    person = get_object_or_404(get_user_model(), pk=article.user_id)
    comment_form = CommentForm() # 댓글 폼
    context = {'article': article, 'comment_form': comment_form, 'comments': comments, 'person': person,}
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.user:
            article.delete()
        else:
            return redirect(article)
    return redirect('articles:index')


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                # hashtag가 달린 글을 수정할 때는 모두 삭제한 후
                # 다시 등록하는 방식으로
                article.hashtags.clear() # 해당 article의 hashtag 전체 삭제
                for word in article.content.split():
                    if word.startswith('#'):
                        hashtag, created = Hashtag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)

                return redirect(article)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {'form': form, 'article': article,}
    return render(request, 'articles/form.html', context)


@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.article_id = article_pk
            comment.save()
    return redirect('articles:detail', article_pk)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        return redirect('articles:detail', article_pk)
    return HttpResponse('You are Unauthorized', status=401)


def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # article = Article.get.all(pk=article_pk)

    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)

    # 해당 게시글에 좋아요를 누른 사람들 중에서 현재 접속유저가 있다면 좋아요를 취소
    # if request.user in article.like_users.all():
    #     article.like_users.remove(request.user) # 좋아요 취소
    # else:
    #     article.like_users.add(request.user) # 좋아요
    return redirect('articles:index')

@login_required
def follow(request, article_pk, user_pk):
    # person : 게시글을 작성한 유저
    person = get_object_or_404(get_user_model(), pk=user_pk)
    # user : 접속 상태인 유저
    user = request.user

    if person != user:
        # Like와 짜는 방법 비슷 (이미 내가(request.user) 팔로우 목록에 존재한다면 팔로우 취소)
        if person.followers.filter(pk=user.pk).exists():
            person.followers.remove(user)
        else:
            person.followers.add(user)
        
    return redirect('articles:detail', article_pk)


def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    articles = hashtag.article_set.order_by('-pk')
    context = {'hashtag': hashtag, 'articles': articles,}
    return render(request, 'articles/hashtag.html', context)

SSAFY/03_django/03_django_form/articles/templates/articles/_article.html
<div class="card mb-3">
  <div class="card-header">
  작성자 : <a class="card-link" href={% url 'accounts:profile' article.user %}> {{ article.user }}</a>
  </div>
  <div class="card-body">
    <h5 class="card-title">글 제목 : {{ article.title }}</h5>
    <p class="card-text">{{ article.pk }}</p>
    <hr>
    <p class="card-text">
      <a href="{% url 'articles:like' article.pk %}">
        {% if user in article.like_users.all %}
          <i class="fas fa-heart fa-lg" style="color: crimson;"></i>
        {% else %}
          <i class="fas fa-heart fa-lg" style="color: black;"></i>
        {% endif %}
      </a>
      {{ article.like_users.all|length }} 명이 이 글을 좋아합니다.
    </p>
    <a href="{{ article.get_absolute_url }}" class="btn btn-primary">DETAIL</a>
  </div>
</div>

SSAFY/03_django/03_django_form/articles/templates/articles/_follow.html
<div class="jumbotron text-center">
  <h1 class="display-4">{{ person.username }}</h1>
  {% with followers=person.followers.all followings=person.followings.all %}
  <p class="lead">
    팔로잉 : {{ followings|length }} / 팔로워 : {{ followers|length }}
  </p>
  <hr class="my-4">
  {% if user != article.user %}
  {% if user in followers %}
  <a class="btn btn-primary btn-lg" href={% url 'articles:follow' article.pk person.pk %} role="button">Unfollow<a>
      {% else %}
      <a class="btn btn-primary btn-lg" href={% url 'articles:follow' article.pk person.pk %} role="button">Follow<a>

          {% endif %}
          {% endif %}
          {% endwith %}
</div>

SSAFY/03_django/03_django_form/articles/templates/articles/_nav.html
{% load gravatar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  {% if user.is_authenticated %}
  <a class="navbar-brand" href={% url 'articles:index' %}>
    <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" width="30" height="30"
      class="d-inline-block align-top" alt="gravatar">
    Hello, {{ user.username }} !
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li>
        <a class="nav-link" href="{% url 'accounts:profile' user.username %}">내 프로필 <span class="sr-only">(current)</span></a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'accounts:update' %}">정보수정 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change_password' %}">비번변경</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      <li class="nav-item">
        <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" class="btn btn-danger">
        </form>
      </li>
    </ul>
  </div>
  {% else %}
  <a class="navbar-brand" href={% url 'articles:index' %}>
    <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80" width="30" height="30"
      class="d-inline-block align-top" alt="gravatar">
    Hello, Stanger !
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li>
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
    </ul>
  </div>
  {% endif %}
</nav>

SSAFY/03_django/03_django_form/articles/templates/articles/base.html
{% load bootstrap4 %}
{% load gravatar %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/dacf7dcd9c.js" crossorigin="anonymous"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  {% include 'articles/_nav.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>

SSAFY/03_django/03_django_form/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load make_link %}
{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <p>{{ article.pk }}</p>
  <p>{{ article.title }}</p>
  <p>{{ article|hashtag_link|safe }}</p>
  <p>{{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
  <p>{{ article.updated_at|date:"M, j, Y" }}</p>
  {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE">
    </form>
  {% endif %}
  <hr>
  <!-- 댓글 출력 -->
  {% for comment in comments %}
    <div>
      댓글 {{ forloop.revcounter }} : {{ comment.content }}
      {% if request.user == comment.user %}
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    </div>
  {% empty %}
    <p><b>댓글이 없습니다.</b></p>
  {% endfor %}
  <hr>
  <!-- 댓글 입력 form -->
  {% if user.is_authenticated %}
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" value="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  {% include 'articles/_follow.html' %}
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

SSAFY/03_django/03_django_form/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block content %}
  {% if request.resolver_match.url_name == 'create' %}
    <h1>CREATE</h1>
  {% else %}
    <h1>UPDATE</h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}
    {% buttons submit="OK" reset="Cancel" %}{% endbuttons %}
  </form>
  
  <hr>
  {% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'articles:index' %}">BACK</a>
  {% else %}
    <a href="{{ article.get_absolute_url }}">BACK</a>
  {% endif %}
{% endblock %}

SSAFY/03_django/03_django_form/articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid text-center my-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">{{ hashtag.content }}</h1>
    <p class="lead">{{ articles|length }} 개의 게시글</p>
  </div>
</div>
<hr>
<h3 class="text-center">{{ hashtag.content }} 를 태그한 글</h3>
<div class="row">
  {% for article in articles %}
  {% with likes=article.like_users.all comments=article.comment_set.all %}
  <div class="col-4 my-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ likes|length }} 명이 좋아요</p>
        <p class="card-text">{{ comments|length }} 개의 댓글</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-success">보러가기</a>
      </div>
    </div>
  </div>
  {% endwith %}
  {% endfor %}
</div>
{% endblock content %}

SSAFY/03_django/03_django_form/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block content %}
  <h1>Articles</h1>
  <p><b>당신의 방문 횟수 : {{ visits_num }}{% if visits_num == 1 %} time{% else %} times{% endif %}</b></p>
  {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}">[NEW]</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요]</a>
  {% endif %}
  <hr>
  {% for article in articles %}
    {% include 'articles/_article.html' %}
  {% endfor %}
{% endblock %}

SSAFY/03_django/03_django_form/articles/templates/articles/test.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
    const test = '11'
    export default {
      name: 'hello'
    }
  </script>
</body>

</html>